project MyTacoFund {
  database_type: 'PostgreSQL'
  Note: '''
        ```typescript
        export interface AccountVerified {
            verifiedEmail: boolean;
            verifiedSMS: boolean;
        }

        export interface Address {
            line1: string;
            line2?: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        }

        export interface SocialProfile {
            clubhouse: string;
            dribbble: string;
            facebook: string;
            github: string;
            instagram: string;
            linkedin: string;
            pinterest: string;
            snapchat: string;
            tiktok: string;
            twitch: string;
            twitter: string;
            youtube: string;
            other: string;
        }
        ```
  '''
}

table account {
    id uuid [pk]
    firstName text [not null]
    lastName text [not null]
    email text [unique, not null]
    phone text
    password text 
    address jsonb [default: null]
    socialProfiles jsonb [default: null]
    accountRole EnumAccountRole [default: 'supporter']
    accountStatus EnumAccountStatus [default: 'active']
    accountVerified jsonb [default: null]
    isActive boolean [default: true]
    passwordChangedAt date [default: null]
    passwordResetToken text [default: null]
    passwordResetExpires date [default: null]
    recordCreated timestamp [default: `now()`]
    recordUpdated timestamp [default: null]
    productList jsonb [ref: < products.id]
}

table products {
    id uuid [pk]
    title text [not null]
    image text
    description text
    productType EnumProductType [default: 'single']
    priceUnit int [default: 5,not null]
    recordCreated timestamp [default: `now()`]
    recordUpdated timestamp [default: null]
    account_id uuid [ref: > account.id]
}

table orders {
    id uuid [pk]
    customer_id uuid [ref: <> account.id, default: null]
    product_id uuid [ref: <> products.id]
    totalCost int [not null]
    recordCreated timestamp [default: `now()`]
    recordUpdated timestamp [default: null]
}

// enums section 
enum  EnumAccountRole {
    employeeAdmin
    employeeSuperAdmin
    creator
    supporter
}

enum EnumAccountStatus {
    active
    archvied
    hold
    inactive
}

enum EnumProductType {
    single
    subscription
}

// virtual fields section